### ISSUE TITLE
OpenROAD-flow repo is down

### ISSUE THREAD

**Issue by lsteveol** [abdelrahmanhosny/DAC-2020-OpenROAD-Tutorial#1]
Also mentioned here (https://github.com/The-OpenROAD-Project/OpenROAD/issues/408) but just creating this for easier reference.

**Comment by kevingo** [comment]
Is there any update information about this issue?

**Comment by kevingo** [comment]
I found the repo is opened in an archived way  : [OpenROAD-flow-public](https://github.com/The-OpenROAD-Project/OpenROAD-flow-public).

**Comment by lsteveol** [comment]
Thanks for the update. I'll close this.
